# Generated by Django 3.2.6 on 2021-09-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210904_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='ho_ten',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='ho_ten',
        ),
    ]
