# Generated by Django 3.2.6 on 2021-09-25 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210905_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramdung',
            name='tramDung_tuyenDuong',
        ),
        migrations.AddField(
            model_name='tuyenduong',
            name='tramDung_tuyenDuong',
            field=models.ManyToManyField(through='index.TramDung_TuyenDuong', to='index.TramDung'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.PositiveIntegerField(default=0)),
                ('chuyen_xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.chuyenxe')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('noi_dung', models.TextField()),
                ('chuyen_xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.chuyenxe')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.PositiveIntegerField(choices=[(0, 'like'), (1, 'dislike')], default=0)),
                ('chuyen_xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.chuyenxe')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
