# Generated by Django 3.2.6 on 2021-09-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210926_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='ho_ten',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='ho_ten',
            field=models.CharField(default='', max_length=256),
        ),
    ]
