# Generated by Django 3.2.6 on 2021-10-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='ngay_sinh',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='ngay_sinh',
            field=models.DateField(null=True),
        ),
    ]
