# Generated by Django 3.2.6 on 2021-10-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20211006_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
