# Generated by Django 3.2.6 on 2021-10-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20211007_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='cmnd',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='cmnd',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
