# Generated by Django 3.2.6 on 2021-10-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20211007_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='benxe',
            name='vi_tri',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
