# Generated by Django 3.2.6 on 2021-10-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_benxe_vi_tri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuyenxe',
            name='tuyen_duong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuyen_duong_chuyen', to='index.tuyenduong'),
        ),
        migrations.AlterField(
            model_name='chuyenxe',
            name='xe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xe_chuyen', to='index.xe'),
        ),
    ]
