# Generated by Django 3.2.6 on 2021-10-18 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20211017_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vexe',
            name='khach_hang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='index.khachhang'),
        ),
    ]
