# Generated by Django 3.2.6 on 2021-10-18 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_alter_vexe_khach_hang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giave',
            name='model_xe',
        ),
        migrations.AddField(
            model_name='giave',
            name='xe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='index.xe'),
        ),
    ]
