# Generated by Django 3.2.6 on 2021-10-27 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='vexe',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='custumer', max_length=10),
        ),
    ]
