# Generated by Django 3.2.6 on 2021-10-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20211027_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='vexe',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vexe',
            name='chuyen_xe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vexes', to='index.chuyenxe'),
        ),
    ]
