# Generated by Django 3.2.6 on 2021-10-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20211028_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='vexe',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
