# Generated by Django 3.2.6 on 2021-11-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_chuyenxe_gio_ket_thuc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tramdung_tuyenduong',
            name='thoi_gian_dung',
            field=models.TimeField(null=True),
        ),
    ]
