# Generated by Django 3.2.6 on 2021-09-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210917_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='courses/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='courese',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='courses/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='courses/%Y/%m'),
        ),
    ]
